### ISSUE TITLE
Seller page wont display header

### ISSUE THREAD

**Issue by refiloemopeloa** [SeanWits/Malumez#11]
Created a header for the seller page and exported it. upon calling it from the seller file, the following error is thrown:
Uncaught runtime errors:
```
×
ERROR
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `App`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `App`.
    at createFiberFromTypeAndProps (http://localhost:3000/static/js/bundle.js:92850:21)
    at createFiberFromElement (http://localhost:3000/static/js/bundle.js:92871:19)
    at reconcileSingleElement (http://localhost:3000/static/js/bundle.js:81970:27)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:82020:39)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:84966:32)
    at updateContextProvider (http://localhost:3000/static/js/bundle.js:86654:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:87069:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:72040:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:72084:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:72141:35)
ERROR
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `App`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `App`.
    at createFiberFromTypeAndProps (http://localhost:3000/static/js/bundle.js:92850:21)
    at createFiberFromElement (http://localhost:3000/static/js/bundle.js:92871:19)
    at reconcileSingleElement (http://localhost:3000/static/js/bundle.js:81970:27)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:82020:39)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:84966:32)
    at updateContextProvider (http://localhost:3000/static/js/bundle.js:86654:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:87069:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:72040:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:72084:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:72141:35)
ERROR
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `App`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `App`.
    at createFiberFromTypeAndProps (http://localhost:3000/static/js/bundle.js:92850:21)
    at createFiberFromElement (http://localhost:3000/static/js/bundle.js:92871:19)
    at reconcileSingleElement (http://localhost:3000/static/js/bundle.js:81970:27)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:82020:39)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:84966:32)
    at updateContextProvider (http://localhost:3000/static/js/bundle.js:86654:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:87069:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:72040:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:72084:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:72141:35)
ERROR
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `App`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `App`.
    at createFiberFromTypeAndProps (http://localhost:3000/static/js/bundle.js:92850:21)
    at createFiberFromElement (http://localhost:3000/static/js/bundle.js:92871:19)
    at reconcileSingleElement (http://localhost:3000/static/js/bundle.js:81970:27)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:82020:39)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:84966:32)
    at updateContextProvider (http://localhost:3000/static/js/bundle.js:86654:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:87069:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:72040:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:72084:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:72141:35)
ERROR
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `App`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `App`.
    at createFiberFromTypeAndProps (http://localhost:3000/static/js/bundle.js:92850:21)
    at createFiberFromElement (http://localhost:3000/static/js/bundle.js:92871:19)
    at reconcileSingleElement (http://localhost:3000/static/js/bundle.js:81970:27)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:82020:39)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:84966:32)
    at updateContextProvider (http://localhost:3000/static/js/bundle.js:86654:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:87069:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:72040:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:72084:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:72141:35)
ERROR
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `App`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `App`.
    at createFiberFromTypeAndProps (http://localhost:3000/static/js/bundle.js:92850:21)
    at createFiberFromElement (http://localhost:3000/static/js/bundle.js:92871:19)
    at reconcileSingleElement (http://localhost:3000/static/js/bundle.js:81970:27)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:82020:39)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:84966:32)
    at updateContextProvider (http://localhost:3000/static/js/bundle.js:86654:7)
    at beginWork (http://localhost:3000/static/js/bundle.js:87069:18)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:91983:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:91253:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:91176:9)
```

**Comment by refiloemopeloa** [comment]
Issue resolved. Issue was caused by exporting seller with brackets
cause of error:
```
export default Seller();
```
fix of error:
```
export default Seller;
```
